App leds
westermo/app-demo pull request #2
Opened 2021-05-18 08:28 UTC by andreasegeberg

2021-05-27 06:06 UTC, troglobit requested changes
There are a few changes that we need to make before merging.  Maybe @wkz has some more thoughts on this.

2021-05-27 06:06 UTC, troglobit commented on board/demo/leds/post-build.sh
> +echo "PRETTY_NAME=\"Leds Demo\""                  >>$TARGET_DIR/etc/os-release
We should probably use the singular form "LED Demo", since it's an abbreviation.

2021-05-27 06:06 UTC, troglobit commented on package/leds/Config.in
> +	  This is the Leds demo app.
Change to: "LED demo application.  This demonstrates how a container application can be used to control one or more LEDs shared by the host system."

2021-05-27 06:06 UTC, troglobit commented on src/leds/LICENSE
> +Copyright (c) 2020 Westermo Network Technologies
Change to 2021 and append AB to the company name.

2021-05-27 06:06 UTC, troglobit commented on src/leds/README.md
> +# Leds application
LED Demo Application

2021-05-27 06:06 UTC, troglobit commented on src/leds/README.md
> +The `Leds` application demonstrates how to read and write to the leds device file to control the physical leds on a device.
s/led/LED/g

=> "The LED Application demonstrates how to control physical LEDs shared by the host system.

2021-05-27 06:06 UTC, troglobit commented on src/leds/README.md
> +From the `Host` a path is shared to the `led device file` for a physical port and the path is then mounted in the container when LXC starts the container.
Same sed expression as above, and also make sure to reflow _all_ paragraphs in the REDME to not overflow 78 character width limit.

2021-05-27 06:06 UTC, troglobit commented on src/leds/README.md
> +On the `Host` symlinks are defined for the device files in `/sys/class/leds/` directory. To create and configure a container application `bar` of image type `leds` follow these steps:
It's OK to write "On the WeOS host system, symlinks are ...".

2021-05-27 06:06 UTC, troglobit commented on src/leds/leds.c
> +		"\n", __progname, __progname, __progname);
Not all LIBC have `__progname`, but the one our toolchains use do.  Just a portability notice for future reference.

2021-05-27 06:06 UTC, troglobit commented on src/leds/leds.c
> +	struct ev_loop *loop;
Coding style: variable declarations should be sorted in a "reverse christmas tree" style.  

E.g.
```
  static char some_buffer[123];
  int foobar;
  char baz;
```

2021-06-03 07:31 UTC, closed without merging

2021-06-03 07:32 UTC, andreasegeberg commented
This branch is replaced by led-relay branch